<a href="https://colab.research.google.com/github/jbvp4116/data-analysis-programming/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [16]:
import numpy as np
np.hstack((a, np.expand_dims(c, axis = 1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [17]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])
x, y

(array([[1, 2, 3]]), array([[4, 5, 6]]))

In [26]:
x.shape, y.shape

((1, 3), (1, 3))

In [28]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [30]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [31]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [32]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [36]:
rg = np.random.default_rng(1)
rg.random() #[0, 1)

0.5118216247002567

In [42]:
rg.random()

0.8277025938204418

In [43]:
rg.random(5)

array([0.40919914, 0.54959369, 0.02755911, 0.75351311, 0.53814331])

In [44]:
rg.random((4, 3))

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299],
       [0.20345524, 0.26231334, 0.75036467],
       [0.28040876, 0.48519097, 0.9807372 ]])

In [45]:
rg.random((4, 3, 2))

array([[[0.96165719, 0.72478994],
        [0.54122686, 0.2768912 ],
        [0.16065201, 0.96992541]],

       [[0.51606859, 0.11586561],
        [0.62348976, 0.77668311],
        [0.6130033 , 0.9172977 ]],

       [[0.03959288, 0.52858926],
        [0.45933588, 0.06234958],
        [0.64132817, 0.85263284]],

       [[0.59294102, 0.26009745],
        [0.83988152, 0.50949588],
        [0.51088888, 0.75303021]]])

In [47]:
rg = np.random.default_rng(1)
rg.integers(0, 10, 3)

array([4, 5, 7])

In [50]:
rg.integers(0, 20, size=(3, 4))

array([[19,  0,  2, 16],
       [18,  4,  6, 17],
       [ 8,  5, 16,  5]])

In [51]:
rg.integers(1, 7, (3, 4))

array([[3, 4, 4, 1],
       [1, 6, 5, 6],
       [4, 5, 2, 3]])

In [55]:
rg = np.random.default_rng(1)
rg.standard_normal(3) # 표준 정규분포 실수 난수

array([0.34558419, 0.82161814, 0.33043708])

In [70]:
rg.standard_normal((25, 4))

array([[-0.67247275,  0.58629342,  0.04893524, -1.10360927],
       [-1.12788718, -0.55551921, -0.676006  ,  1.09030239],
       [ 1.3755383 ,  0.86855962,  0.35786889, -0.42823821],
       [ 0.05448321,  0.88470701,  2.13097223,  0.91289921],
       [-0.28041214,  0.03802508, -0.4825449 , -0.78239858],
       [-0.184242  ,  0.19561469,  1.83590159,  0.05203247],
       [ 1.35735807,  1.76748908,  0.07880787,  1.60779889],
       [ 0.7149354 , -0.41753529,  0.26518002,  0.02287782],
       [-0.23233903, -0.19878123,  0.1442093 ,  0.43418114],
       [-0.88488188, -0.00938766, -1.52235502,  0.2607955 ],
       [ 0.62359948,  0.16395484,  0.28585315,  0.5899431 ],
       [-0.66510084, -0.23904886,  0.51092204,  1.00188573],
       [ 0.3949214 ,  2.55285942, -0.09136057,  0.99966043],
       [ 1.26672768, -0.13376985, -0.82051288, -1.18260293],
       [ 0.162277  ,  1.11029195,  0.2716684 ,  0.17285608],
       [-0.37921388,  0.56102973, -2.13583105,  0.23237325],
       [ 0.02812631, -1.

## 배열 결합 연습

In [71]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [73]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [75]:
np.vstack((a, b, c)) # 1D -> 2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
np.vstack((p, q, r)) #2D 유지

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [79]:
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
np.hstack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [81]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [83]:
np.column_stack((a, b, c)) # 1D -> 2D

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [85]:
np.column_stack((p, q, r)) # 2D 유지

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [86]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [88]:
np.concatenate((p, q, r), axis = 1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [89]:
np.concatenate((p, q, r), axis = None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [90]:
np.c_[a, b, c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [91]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [92]:
np.r_[a, b, c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [94]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [100]:
np.vstack((p, q, r)).reshape(3, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [103]:
np.hstack((p, q, r)).reshape((2, 1, 9))

array([[[ 1,  2,  3, 11, 12, 13, 21, 22, 23]],

       [[ 4,  5,  6, 14, 15, 16, 24, 25, 26]]])